In [2]:
import os
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

True

In [32]:
df = pd.read_csv(os.getenv("ONLINE_RETAIL2_PATH"), encoding='ISO-8859-1')

# Estructura y tipos
print(df.info())
print("\nPorcentaje de nulos por columna\n", df.isnull().mean())
print("\nNumero de duplicados en el DF: ", df.duplicated().sum())
print("\nPorcentaje de duplicados en Invoice\n", df['Invoice'].duplicated().mean())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB
None

Porcentaje de nulos por columna
 Invoice        0.000000
StockCode      0.000000
Description    0.004105
Quantity       0.000000
InvoiceDate    0.000000
Price          0.000000
Customer ID    0.227669
Country        0.000000
dtype: float64

Numero de duplicados en el DF:  34335

Porcentaje de duplicados en Invoice
 0.949756926129715

Customer_ID tiene 22.7% de nulos. <br> <br>
Invoice tiene un alto porcentaje de duplicados (94.9%) por lo que es muy probable que los repetidos sean otros items del mismo Invoice

In [42]:
df[df.duplicated(keep=False)].sort_values('Invoice').head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
669,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom

HALLAZGO: Las filas duplicadas representan el mismo registro capturado dos veces (ejemplo: indice 362 y 385). Candidatas a deduplicacion en capa Silver.

In [21]:
# Calidad de filas
print("\nNumero de filas con Quantity negativo: ", (df["Quantity"] < 0).sum())
print("\nNumero de filas con Price negativo: ", (df["Price"] <= 0).sum())
print("\nNumero de cancelaciones: ", (df['Invoice'].astype(str).str.startswith('C')).sum())

neg_qty_cancelled = df[(df['Quantity'] < 0) & (df['Invoice'].str.startswith('C'))]
print(neg_qty_cancelled)

neg_qty_no_cancel = df[(df['Quantity'] < 0) & (~df['Invoice'].astype(str).str.startswith('C'))]
print(neg_qty_no_cancel)

Numero de filas con Quantity negativo:  22950

Numero de filas con Price negativo:  6207

Numero de cancelaciones:  19494
         Invoice StockCode                       Description  Quantity  \
178      C489449     22087          PAPER BUNTING WHITE LACE       -12
179      C489449    85206A      CREAM FELT EASTER EGG BASKET        -6
180      C489449     21895     POTTING SHED SOW 'N' GROW SET        -4
181      C489449     21896                POTTING SHED TWINE        -6
182      C489449     22083        PAPER CHAIN KIT RETRO SPOT       -12
...          ...       ...                               ...       ...
1065910  C581490     23144   ZINC T-LIGHT HOLDER STARS SMALL       -11
1067002  C581499         M                            Manual        -1
1067176  C581568     21258        VICTORIAN SEWING BOX LARGE        -5
1067177  C581569     84978  HANGING HEART JAR T-LIGHT HOLDER        -1
1067178  C581569     20979     36 PENCILS TUBE RED RETROSPOT        -5

                 InvoiceDate   Price  Customer ID         Country
178      2009-12-01 10:33:00    2.95      16321.0       Australia
179      2009-12-01 10:33:00    1.65      16321.0       Australia
180      2009-12-01 10:33:00    4.25      16321.0       Australia
181      2009-12-01 10:33:00    2.10      16321.0       Australia
182      2009-12-01 10:33:00    2.95      16321.0       Australia
...                      ...     ...          ...             ...
1065910  2011-12-09 09:57:00    0.83      14397.0  United Kingdom
1067002  2011-12-09 10:28:00  224.69      15498.0  United Kingdom
1067176  2011-12-09 11:57:00   10.95      15311.0  United Kingdom
1067177  2011-12-09 11:58:00    1.25      17315.0  United Kingdom
1067178  2011-12-09 11:58:00    1.25      17315.0  United Kingdom

[19493 rows x 8 columns]
        Invoice StockCode   Description  Quantity          InvoiceDate  Price  \
263      489464     21733  85123a mixed       -96  2009-12-01 10:52:00    0.0
283      489463     71477         short      -240  2009-12-01 10:52:00    0.0
284      489467    85123A   21733 mixed      -192  2009-12-01 10:53:00    0.0
470      489521     21646           NaN       -50  2009-12-01 11:44:00    0.0
3114     489655     20683           NaN       -44  2009-12-01 17:26:00    0.0
...         ...       ...           ...       ...                  ...    ...
1060794  581210     23395         check       -26  2011-12-07 18:36:00    0.0
1060796  581212     22578          lost     -1050  2011-12-07 18:38:00    0.0
1060797  581213     22576         check       -30  2011-12-07 18:38:00    0.0
1062371  581226     23090       missing      -338  2011-12-08 09:56:00    0.0
1064386  581422     23169       smashed      -235  2011-12-08 15:24:00    0.0

         Customer ID         Country
263              NaN  United Kingdom
283              NaN  United Kingdom
284              NaN  United Kingdom
470              NaN  United Kingdom
3114             NaN  United Kingdom
...              ...             ...
1060794          NaN  United Kingdom
1060796          NaN  United Kingdom
1060797          NaN  United Kingdom
1062371          NaN  United Kingdom
1064386          NaN  United Kingdom

[3457 rows x 8 columns]

HALLAZGO: Las ordenes con Quantity , con StockCode e Invoice valido sin haber sido canceladas muestran corrupcion en los campos de Description y Customer ID. Siendo un total de 3,457 filas corruptas (ajustes internos de inventario, mermas, productos dañados, etc).<br> <br>
Ademas estas filas presentan Customer ID nulos, lo que explica el procentaje de 22.7% nulos en la columna Customer ID. <br> <br>
A diferencia de ordenes canceladas con Quantity negativa que si muestran campos de Description, Customer ID y StockCode validos.

In [14]:
# StockCode sospechosos
print(df['StockCode'].value_counts().to_string())

StockCode
85123A          5829
22423           4424
85099B          4216
21212           3318
20725           3259
84879           2960
47566           2768
21232           2747
22197           2549
22383           2540
20727           2529
21931           2434
22386           2347
22469           2325
22411           2297
84991           2271
22382           2251
22384           2230
21080           2224
22086           2217
20914           2213
21034           2199
22139           2196
21754           2192
20728           2185
22138           2154
22457           2152
20724           2138
POST            2122
22470           2117
82482           2116
82494L          2108
21977           2092
20726           2050
21790           1988
85099C          1952
22178           1934
21181           1920
85099F          1916
84946           1904
21733           1903
22077           1858
22112           1847
22111           1846
22355           1832
22666           1810
21755           1798
20685           1786
22090           1752
21843           1734
21175           1730
48138           1716
22114           1711
21929           1681
22356           1658
21231           1641
20719           1641
22379           1629
21731           1628
21928           1612
84992           1572
22910           1564
22699           1553
21213           1551
85152           1523
84978           1518
21166           1502
21485           1501
84836           1499
22149           1496
22697           1491
22727           1490
84970S          1477
22326           1477
22720           1477
20972           1473
20712           1468
22083           1466
22629           1449
DOT             1446
20723           1443
22630           1422
M               1421
22551           1399
82580           1397
21791           1395
82486           1394
48194           1393
22865           1388
22726           1386
21975           1386
20713           1385
21930           1375
22554           1366
22189           1352
21621           1344
84755           1330
48187           1321
22960           1315
84378           1309
21559           1304
22961           1303
22624           1299
22385           1295
22556           1289
84029E          1279
82483           1279
22558           1275
23203           1267
82583           1266
22952           1264
22866           1262
22147           1257
82600           1250
22328           1243
20718           1242
22467           1239
82484           1235
79321           1222
22557           1222
22867           1220
20971           1219
22585           1216
22367           1215
21535           1212
22219           1206
21889           1206
21210           1203
22909           1203
84692           1198
22553           1197
21524           1190
21174           1185
22659           1185
47591D          1184
22352           1180
23298           1179
21314           1169
85150           1167
84380           1162
21523           1161
22417           1158
21481           1152
84997D          1146
22381           1138
23209           1135
22029           1128
84029G          1124
84970L          1119
22698           1118
22993           1111
22113           1102
21936           1095
21915           1095
22835           1094
23206           1084
20711           1083
21429           1080
15056N          1078
71459           1071
23084           1067
84997B          1066
22196           1062
84077           1056
21479           1054
22173           1051
22082           1045
84988           1045
22662           1045
21533           1045
22728           1041
22633           1038
22617           1037
22297           1035
22625           1029
22555           1028
85066           1025
21172           1021
21908           1021
21155           1021
48185           1020
15036           1020
21165           1020
21914           1019
21094           1012
22150           1012
23199           1009
20676           1007
21976           1006
22348           1003
21527            996
21217            995
20975            994
84997C           994
22502            992
21156            983
21035            974
72741            971
22646            970
21985            968
21154            963
22561            957
21238            956
21218            955
21935            953
82581            952
21868            952
22487            951
20750            950
22294            942
22568            941
71477            940
22667            939
22694            939
21484            939
23301            937
85014B           933
23201            930
22507            930
22632            926
22621            925
21891            923
21121            923
15056BL          923
22413            922
23245            919
22087            910
22456            908
47590B           906
84406B           904
22620            902
20974            897
85049E           897
22652            897
23202            896
21892            894
22296            894
20754            890
22616            888
22577            886
22212            886
22907            884
48184            881
21086            879
21900            878
21888            874
22722            874
22570            872
22027            871
21668            867
21430            865
21912            863
22273            862
22195            862
21669            862
22759            861
84375            861
22464            855
22427            854
21216            853
21122            853
22569            853
21871            852
22084            852
84347            849
21672            849
22488            842
82582            842
22595            840
22271            839
22501            838
84987            835
21169            834
21918            832
21531            831
22578            830
21974            828
82552            824
21558            821
22900            821
22489            819
21498            818
23355            813
22748            811
20749            810
22730            808
71053            808
21877            807
22734            807
21670            807
22158            806
22645            805
21673            804
47566B           804
21907            804
21539            800
84949            799
21240            794
22499            791
22966            790
22505            788
20677            788
22560            787
22144            786
20717            786
22752            785
22424            784
21239            782
22055            782
23300            780
23207            780
82551            779
22607            777
22745            775
21136            774
22064            774
22295            772
21982            770
21078            770
21671            768
21955            768
84050            767
22151            765
22776            764
22492            763
22969            762
22619            758
22198            758
22665            757
84520B           756
22169            756
48111            755
22549            754
21916            753
84596B           753
20979            750
84947            749
20679            749
21164            747
23284            746
47559B           745
22333            745
21934            744
22749            744
22371            740
22131            739
23344            739
21901            739
22508            737
35970            736
82578            733
21385            733
85049A           728
22804            727
84945            725
20973            724
22380            723
22030            720
22171            720
20675            717
48188            717
22079            714
85014A           710
47590A           709
22301            707
21980            706
21259            706
22663            705
22327            704
22274            704
22627            703
22631            702
84032A           702
21506            698
21326            696
22766            696
21992            695
22109            695
22750            695
21937            694
22834            693
23208            692
21098            692
22429            689
21870            688
22227            685
21328            685
20983            682
22951            681
21989            677
21380            677
21242            676
22729            674
35961            669
21932            668
21622            668
22605            667
22191            667
84832            666
21770            665
21876            665
22644            664
22637            663
21899            662
21137            661
22661            661
21124            660
21874            660
22654            660
23307            659
22193            658
23321            657
22940            657
22739            655
21933            655
22037            654
21411            651
20828            649
22156            647
21108            647
84536A           646
22431            646
22358            645
20969            644
22088            641
22141            640
21509            638
84032B           635
20682            633
22534            631
22329            631
22418            627
84596F           622
22692            622
84997A           621
21756            619
22584            619
21390            617
22170            616
21258            615
20982            614
22746            611
22622            610
16237            609
23200            609
22174            607
20970            605
85048            604
21993            604
21658            603
22725            601
22179            600
22579            600
21704            598
21033            597
21981            597
21703            596
21890            596
22061            595
37448            595
23204            594
22668            594
23322            594
21507            592
22366            591
22188            590
85232B           590
20978            586
21329            585
37370            582
22041            582
22634            579
22192            579
22435            577
22072            576
22528            575
22983            574
22300            574
22303            573
22623            573
21257            573
22563            573
22602            571
37449            570
22089            569
21116            569
21623            568
21041            568
21519            567
23240            567
23293            567
21260            567
22378            566
22649            565
22851            564
21381            564
20751            563
48129            563
22998            557
22142            557
22571            557
21700            556
22110            554
22080            553
22335            553
85049G           553
20961            551
21508            550
22941            550
22567            550
21714            546
22837            546
22361            544
22771            544
20963            544
82599            544
84792            543
22419            543
22737            541
20981            540
22795            540
37503            540
22432            540
22073            539
22738            539
21561            538
22636            538
22059            535
22635            535
21494            535
22847            534
21844            534
22755            534
84030E           534
22712            533
21179            532
85049C           529
21114            528
72351B           526
22844            526
22161            526
21544            525
22754            524
22580            524
22812            524
48173C           523
22065            522
22028            522
21327            521
20829            520
21990            520
21071            519
85199S           519
72760B           519
22465            518
21967            518
22588            516
21592            516
22908            516
22115            515
21243            514
22353            514
20977            510
48116            510
21746            509
23243            509
22441            509
22906            509
21716            509
22078            509
85061W           508
21902            508
22988            506
21745            505
22207            503
23198            503
23356            502
82567            502
23343            501
22898            500
22494            499
21500            498
21786            497
22357            497
22530            497
22904            497
22751            496
21715            496
21787            495
84510A           494
84270            493
21832            493
22360            493
23263            492
21428            491
21917            491
22241            490
21497            490
22444            489
85227            488
21986            488
21866            487
21577            485
22121            484
22045            483
17003            483
35400            482
84971S           481
21718            481
22791            481
22185            480
23205            480
20674            479
79323W           478
85175            475
22236            475
22130            474
21407            473
22816            473
21833            472
79000            472
21499            471
15060B           471
21984            470
22437            468
37446            467
84580            467
21244            467
22548            465
20992            464
22244            464
22365            463
22596            462
22716            461
22208            461
22669            461
21452            461
20966            461
47556B           460
22331            460
23295            460
23170            458
22398            458
22180            456
21340            455
22855            455
22600            455
22690            455
22024            454
21906            453
22550            453
23182            452
22374            452
22493            451
22670            450
22601            449
22899            449
22736            449
16161P           447
21313            447
22377            446
22023            446
22574            446
21115            445
22593            444
22840            443
22245            442
22895            442
21875            442
22964            441
85040A           441
37450            441
22433            441
21363            439
23173            438
22468            438
21135            437
22818            435
22531            435
22421            435
23309            435
22573            434
21903            434
23493            433
21811            433
21864            433
22747            432
22594            432
21829            432
21713            431
22753            431
22485            431
21042            430
22784            430
21988            429
16156S           427
22243            426
23439            425
23319            425
79067            425
47568            424
85049D           423
22199            423
22224            422
22996            422
22466            421
22412            421
21878            421
22845            420
84536B           419
21624            419
84839            419
22278            419
72351A           418
23328            418
22603            418
85053            417
22581            416
22302            416
22318            415
23313            415
22809            415
84509A           414
22203            414
75049L           414
85038            413
21591            413
85231B           412
22222            412
22562            412
22943            411
22315            410
22491            408
22813            408
21068            408
22107            407
22962            406
22606            406
22798            405
22187            405
21578            404
21781            404
35004C           404
22653            403
46000S           403
21922            403
37447            403
22572            403
21987            403
20668            402
22768            402
22242            401
22132            401
85174            400
10002            400
22536            400
22276            399
22283            398
21584            396
22215            396
22332            396
22426            396
22979            395
22460            395
21777            395
22076            394
22614            394
84880            394
23308            394
23108            393
22364            392
22521            391
23318            391
22498            390
22439            390
51014A           390
23296            389
22430            389
23171            388
22713            388
22075            387
22672            387
22063            386
21488            386
47599A           386
21679            386
22349            386
23103            386
22583            386
22520            386
21534            386
22175            385
21774            385
47567B           385
21186            384
22896            384
22155            383
22989            383
23256            382
20658            382
22120            382
72807C           381
22945            381
21810            381
21563            381
23241            379
22743            379
20752            379
21495            379
22422            378
22846            378
46000M           378
79029            377
22119            376
22035            373
22537            373
22628            372
20681            372
22200            372
22950            372
20665            372
22026            371
22810            371
22523            371
22575            371
22186            371
47593B           370
85062            370
22483            370
22626            370
37495            370
35471D           370
47580            369
21272            369
84828            369
23294            369
22714            368
21356            368
22154            368
22564            367
22576            367
22992            367
21355            366
22733            366
22963            365
23351            364
22094            363
22544            362
85042            362
23168            361
15056P           361
22168            361
84596G           361
84969            361
22732            360
22817            360
21911            359
23192            359
21730            358
21625            358
85184C           357
23236            356
23581            355
22968            354
22693            354
79323P           354
22796            353
23169            353
21447            352
84078A           351
22350            351
23311            351
21872            350
85049B           350
22525            350
23349            350
22522            349
21383            349
22815            349
20996            348
23077            348
21802            347
23503            347
22801            347
23320            346
84535B           346
21803            346
21110            345
23175            345
23275            345
22070            345
85049H           343
22091            343
21983            343
22758            343
23266            343
21463            342
22098            342
23174            342
23188            342
85178            341
21107            341
10135            341
21504            340
23583            339
22772            339
22133            339
22587            338
22262            338
21158            337
23353            337
21880            337
84031A           337
22781            335
21470            335
23354            335
85206A           333
22819            333
20967            332
22757            332
47504K           332
22841            332
22135            332
22449            331
85017B           331
85049F           330
16235            330
21224            330
84279P           330
22231            329
20886            329
21471            329
22311            329
22275            329
22970            328
22095            328
22167            328
22744            328
22767            327
21818            327
22676            325
22440            325
21867            325
22478            324
16161U           323
21773            322
22892            322
22272            321
22775            321
23247            320
85176            320

StockCode sospechosos: <br>
POST = 2122 <br>
DOT = 1446 <br>
M = 1421 <br>
BANK CHARGES = 102 <br>

In [15]:
print(df['Country'].unique())

['United Kingdom' 'France' 'USA' 'Belgium' 'Australia' 'EIRE' 'Germany'
 'Portugal' 'Japan' 'Denmark' 'Nigeria' 'Netherlands' 'Poland' 'Spain'
 'Channel Islands' 'Italy' 'Cyprus' 'Greece' 'Norway' 'Austria' 'Sweden'
 'United Arab Emirates' 'Finland' 'Switzerland' 'Unspecified' 'Malta'
 'Bahrain' 'RSA' 'Bermuda' 'Hong Kong' 'Singapore' 'Thailand' 'Israel'
 'Lithuania' 'West Indies' 'Lebanon' 'Korea' 'Brazil' 'Canada' 'Iceland'
 'Saudi Arabia' 'Czech Republic' 'European Community']

Pasies sospechosos: <br>
EIRE - RSA

In [17]:
print(df['InvoiceDate'].min(), " -> ", df['InvoiceDate'].max())

2009-12-01 07:45:00  ->  2011-12-09 12:50:00

In [66]:
print(df.nlargest(5, 'Price'))
print(df.nsmallest(5, 'Price'))

         Invoice     StockCode   Description  Quantity          InvoiceDate  \
748142   C556445             M        Manual        -1  2011-06-10 15:31:00
241824   C512770             M        Manual        -1  2010-06-17 16:52:00
241827    512771             M        Manual         1  2010-06-17 16:53:00
320581   C520667  BANK CHARGES  Bank Charges        -1  2010-08-27 13:42:00
1050063  C580605     AMAZONFEE    AMAZON FEE        -1  2011-12-05 11:36:00

            Price  Customer ID         Country
748142   38970.00      15098.0  United Kingdom
241824   25111.09      17399.0  United Kingdom
241827   25111.09          NaN  United Kingdom
320581   18910.69          NaN  United Kingdom
1050063  17836.46          NaN  United Kingdom
        Invoice StockCode      Description  Quantity          InvoiceDate  \
179403  A506401         B  Adjust bad debt         1  2010-04-29 13:36:00
276274  A516228         B  Adjust bad debt         1  2010-07-19 11:24:00
403472  A528059         B  Adjust bad debt         1  2010-10-20 12:04:00
825444  A563186         B  Adjust bad debt         1  2011-08-12 14:51:00
825445  A563187         B  Adjust bad debt         1  2011-08-12 14:52:00

           Price  Customer ID         Country
179403 -53594.36          NaN  United Kingdom
276274 -44031.79          NaN  United Kingdom
403472 -38925.87          NaN  United Kingdom
825444 -11062.06          NaN  United Kingdom
825445 -11062.06          NaN  United Kingdom

In [60]:
print("Cancelaciones con Customer ID nulo: ", neg_qty_cancelled['Customer ID'].isnull().sum())

print("StockCode Administrativo + Cancelaciones con Customer ID nulo")
print(neg_qty_cancelled[neg_qty_cancelled['Customer ID'].isnull()]['StockCode'].value_counts())

Cancelaciones con Customer ID nulo:  749
StockCode Administrativo + Cancelaciones con Customer ID nulo
StockCode
M               138
S               101
BANK CHARGES     61
POST             48
AMAZONFEE        39
               ...
21527             1
72802A            1
21102             1
90029             1
22169             1
Name: count, Length: 312, dtype: int64

HALLAZGO: El indicador principal si una orden es por parte de un cliente (Valida / Cancelada) es por medio de un StockCode numerico. Adedmas de un Invoice 'C' con Quantity negativa para cancelaciones validas.<br><br>
Una orden puede tener Quantity negativo pero no clasificarse como canceladas y tener StockCode numerico. Lo que representa un ajuste administrativo.

In [104]:
df[(df['Invoice'].astype(str).str.startswith('C')) & (df['Quantity'] >= 0)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
76799,C496350,M,Manual,1,2010-02-01 08:24:00,373.57,NaN,United Kingdom

In [105]:
print(df['Country'].unique())

['United Kingdom' 'France' 'USA' 'Belgium' 'Australia' 'EIRE' 'Germany'
 'Portugal' 'Japan' 'Denmark' 'Nigeria' 'Netherlands' 'Poland' 'Spain'
 'Channel Islands' 'Italy' 'Cyprus' 'Greece' 'Norway' 'Austria' 'Sweden'
 'United Arab Emirates' 'Finland' 'Switzerland' 'Unspecified' 'Malta'
 'Bahrain' 'RSA' 'Bermuda' 'Hong Kong' 'Singapore' 'Thailand' 'Israel'
 'Lithuania' 'West Indies' 'Lebanon' 'Korea' 'Brazil' 'Canada' 'Iceland'
 'Saudi Arabia' 'Czech Republic' 'European Community']

In [63]:
# Todos los StockCode que no siguen el patrón de producto (dígitos, con o sin letra final)
stockcodes_admin = df[~df['StockCode'].str.match(r'^\d{5}[A-Za-z]?$')]['StockCode'].value_counts()
print(stockcodes_admin)

StockCode
POST         2122
DOT          1446
M            1421
15056BL       923
C2            282
             ...
DCGS0074        1
DCGS0073        1
DCGS0071        1
DCGS0066P       1
DCGS0067        1
Name: count, Length: 68, dtype: int64

In [96]:
print(df[df['StockCode'].str.startswith('DCGS')])
print(df[(df['StockCode'] == '15056BL') & (df['Description'].isna())])
print(df[(df['StockCode'].str.startswith('DCGS')) & (df['Description'].isin(['update', 'ebay']))][['StockCode', 'Description']].drop_duplicates())

        Invoice  StockCode                   Description  Quantity  \
2377     489597   DCGS0058              MISO PRETTY  GUM         1
2378     489597   DCGS0068             DOGS NIGHT COLLAR         1
8371     490074   DCGS0004    HAYNES CAMPER SHOULDER BAG         1
8372     490074   DCGS0058              MISO PRETTY  GUM         1
8373     490074   DCGS0076  SUNJAR LED NIGHT NIGHT LIGHT         1
...         ...        ...                           ...       ...
843773   564825  DCGSSGIRL               GIRLS PARTY BAG         1
891427   568716   DCGSSBOY                BOYS PARTY BAG         2
933664   571931  DCGSSGIRL               GIRLS PARTY BAG         1
1000063  576840  DCGSSGIRL               GIRLS PARTY BAG         1
1044172  580115   DCGSSBOY                BOYS PARTY BAG         1

                 InvoiceDate  Price  Customer ID         Country
2377     2009-12-01 14:28:00   0.83          NaN  United Kingdom
2378     2009-12-01 14:28:00   8.65          NaN  United Kingdom
8371     2009-12-03 14:39:00  17.35          NaN  United Kingdom
8372     2009-12-03 14:39:00   0.83          NaN  United Kingdom
8373     2009-12-03 14:39:00  16.48          NaN  United Kingdom
...                      ...    ...          ...             ...
843773   2011-08-30 12:26:00   3.29          NaN  United Kingdom
891427   2011-09-28 16:13:00   3.29          NaN  United Kingdom
933664   2011-10-19 16:59:00   3.29          NaN  United Kingdom
1000063  2011-11-16 15:23:00   3.29          NaN  United Kingdom
1044172  2011-12-01 16:22:00   3.29          NaN  United Kingdom

[158 rows x 8 columns]
       Invoice StockCode Description  Quantity          InvoiceDate  Price  \
100348  498881   15056BL         NaN        90  2010-02-23 12:52:00    0.0

        Customer ID         Country
100348          NaN  United Kingdom
        StockCode Description
241371   DCGSSBOY      update
241372  DCGSSGIRL      update
804712   DCGS0073        ebay
804716   DCGS0069        ebay
804717   DCGS0068        ebay
804718   DCGS0067        ebay
804719   DCGS0003        ebay

NOTAS FINALES: <br>
Las ordenes de clientes sin cancelacion son aquellas con un StockCode que incluya 4 digitos, Quantity positivo y una Description notnull. <br><br>
Las excepciones erroneas son: <br>
- Description == 'update'
- Description == 'ebay' se descarta al tener Quantity negativo sin contar con 'C' en Invoice <br> <br>

Las excepciones validas son:
- StockCode == 'DCGSSBOY'
- StockCode == 'DCGSSGIRL'

En caso de cancelaciones validas son aquellas que incluyan 'C' en Invoice ademas de un StockCode con 4 digitos.